name: terraform-dev

on:
  push:
    branches:
      - "feature/**"
      - "main"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.IAM_ROLE }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: envs/dev
        run: terraform init

      - name: Terraform Validate
        working-directory: envs/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: envs/dev
        run: terraform plan

      # - name: Terraform Apply
      #   if: startsWith(github.ref_name, 'feature/')
      #   working-directory: envs/dev
      #   run: terraform apply -auto-approve 
        
      - name: Terraform Destroy
        working-directory: envs/dev
        run: terraform destroy -auto-approve